// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EfCoreApp.Sdk.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AddProductResponse
    {
        /// <summary>
        /// Initializes a new instance of the AddProductResponse class.
        /// </summary>
        public AddProductResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddProductResponse class.
        /// </summary>
        public AddProductResponse(int? productId = default(int?))
        {
            ProductId = productId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int? ProductId { get; set; }

    }
}
