using System;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreWebApi20.Controllers
{
    [Route("api/[controller]")]
    public class ExceptionController : Controller
    {
        [HttpGet]
        public string Get()
        {
            throw new Exception("This is a dummy exception generated by GET method.");
        }

        [HttpPost]
        public void Post()
        {
            throw new Exception("This is a dummy exception generated by POST method.");
        }
    }
}
