// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AspNetCoreSwagger.Sdk.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CartItem
    {
        /// <summary>
        /// Initializes a new instance of the CartItem class.
        /// </summary>
        public CartItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CartItem class.
        /// </summary>
        public CartItem(int? cartId = default(int?), int? productId = default(int?), string description = default(string), double? price = default(double?), int? quantity = default(int?))
        {
            CartId = cartId;
            ProductId = productId;
            Description = description;
            Price = price;
            Quantity = quantity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cartId")]
        public int? CartId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

    }
}
